AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creates a S3 bucket and KMS key in every account with the purpose of storing Terraform bootstrap state.

Parameters:
  GithubActionsRoleArn:
    Type: String
    Description: Name for the GithubActionsRoleArn that can read state

Resources:
  S3BucketSource:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  S3BucketSourcePolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    Properties:
      Bucket: !Ref S3BucketSource
      PolicyDocument:
        Statement:
          - Sid: EnforcedTLS
            Effect: Deny
            Action: s3:*
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${S3BucketSource}
              - !Sub arn:${AWS::Partition}:s3:::${S3BucketSource}/*
            Principal: "*"
            Condition:
              Bool:
                aws:SecureTransport: false
          - Sid: DenyOutdatedTLS
            Effect: Deny
            Action: s3:*
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${S3BucketSource}
              - !Sub arn:${AWS::Partition}:s3:::${S3BucketSource}/*
            Principal: "*"
            Condition:
              NumericLessThan:
                s3:TlsVersion: "1.2"
          - Sid: RootAccess
            Effect: Allow
            Action: s3:*
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${S3BucketSource}
              - !Sub arn:${AWS::Partition}:s3:::${S3BucketSource}/*
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root

          - Sid: Allow bucket object access for Github Actions state role
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:DeleteObject
              - s3:GetObject
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${S3BucketSource}/*
            Principal:
              AWS: !Ref GithubActionsRoleArn

          - Sid: Allow bucket list access for Github Actions state role
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketVersioning
              - s3:GetBucketPolicy
              - s3:GetEncryptionConfiguration
              - s3:GetBucketPublicAccessBlock
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${S3BucketSource}
            Principal:
              AWS: !Ref GithubActionsRoleArn
